### ISSUE TITLE
system claimrewards - Not working..

### ISSUE THREAD

**Issue by samspk** [Telos-Foundation/telos#13]
Hello, today system claimrewards is not working...
Attached!

![claimrewards](https://user-images.githubusercontent.com/39917017/43459631-5e79378a-94ce-11e8-85a8-e999b244de2e.jpg)

**Comment by craigbranscom** [comment]
This is an assertion failure. Did you call claimrewards within the last 24 hours? If so then this is expected behavior.

**Comment by marlonwilliams** [comment]
Had no issues running claimrewards

<img width="1670" alt="screen shot 2018-08-01 at 4 39 38 am" src="https://user-images.githubusercontent.com/487376/43510883-01fa6994-9545-11e8-8248-a45ed78af8b1.png">

**Comment by samspk** [comment]
ol... MAybe I called it many times per 24 hours....

**Comment by samspk** [comment]
Yes, from my other test node it is working....

**Comment by ARoomWithABue** [comment]
It looks like this issue has been resolved. Producers are unable to call claimrewards using the same account with a single 24 hour period.
