### ISSUE TITLE
Build, Install and Configuration Instructions

### ISSUE THREAD

**Issue by eossweden** [Telos-Foundation/telos#2]
Hello

Can you please describe the Build, Install and Configuration Process/Instructions (just like it is described in the EOS Documentation)?

**Comment by craigbranscom** [comment]
I've updated our README with instructions on how to Install, Build, Configure, and Register on the testnet. If you run into any issues hop on our telegram or check the testnet monitor, we'd be happy to help.

**Comment by finddabug** [comment]
Where does one find the instructions now? It's not in the main README.md file.

**Comment by Kinzowa** [comment]
How I can install the Telos wallet on my Ubuntu 18.04 ? the README.md states to use yarn package-linux but such file doesn't exist.

Thanks

```
xxx:~/Sqrl$ yarn package-linux
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'package-linux'
xxx:~/Sqrl$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```
