### ISSUE TITLE
Producer Schedule Rotation Change

### ISSUE THREAD

**Issue by ARoomWithABue** [Telos-Foundation/telos#3]
- Research producer_plugin.cpp, controller.cpp, chain_plugin.cpp
- Rewrite controller::set_proposed_producers and the privileged.h set_proposed_producers function prototype. Perhaps write an overload with optional parameters. 
- Rewrite system_contract::update_elected_producers() action to send the list of standby producers.
- Update producer_plugin::schedule_production_loop() to include producer schedule rotation code.

**Comment by eedsilva** [comment]
Ultimately, we designed a different approach that didn't involve changing any of the core files listed above. We found that we could get the desired functionality with the lowest overhead in just the `eosio.system` contract.

All of the changes were made on `system_contract::update_elected_producers()` method. In this method we filter by active and voted producers to identify the top 21 BPs and the following 30 SBPs. After the rotation, a new schedule is proposed, once the proposal is accepted the `chain::controller` will naturally elevate that proposed schedule to pending and then active status. 

A new `rotations` table was defined, where the current BP and SBP references are stored for later computation.

### Code explanation

We defined two, bp indexes, two `block_time_stamp`s and two `account_name`s in the `rotations` table. We verify if there are more than 21 producers to populate the table. In case there are more than 21 BPs we update the table with the respective indexes, account names of BPs that are being rotated and the timestamp for the future rotation. 

[Code reference](https://github.com/Telos-Foundation/telos/blob/master/contracts/eosio.system/voting.cpp#L90)
