### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by ARoomWithABue** [Telos-Foundation/telos#39]
The current plan is to leverage goodblock's internal docker swarm, with git flow and Travis. When new commits are detected in our developer branch. Travis will then start a process which will build the source, start unit tests, then construct a private cluster in our docker swarm. A report will be generated and make public for those that are interested in the process.

![hotm deployment chart](https://user-images.githubusercontent.com/39499751/44441593-3d71cd80-a582-11e8-86fe-8772059c8278.png)

**Comment by oviwankenobi** [comment]
was the alternative to start a build+tests for each PR considered?

**Comment by infinidi** [comment]
Hi @oviwankenobi - we've had a brief discussion at a dev meeting a week ago and thought that at this stage given various resources and interests different bp's can work or different cicd systems and then we can can see what works what does not and go from there.

We at infinitybloc are working on a kubernetes build and test infrastructure on GCP + GKE probably first to get the upstream ".buildkite" working to have that compatibility and ability to re-test if necessary and then enhance it. We can enhance it from there. I'm definitely thinking of having an "on each PR" build cadence.

**Comment by ARoomWithABue** [comment]
@oviwankenobi I'll add that to our CI/CD design. I think having new PRs automatically built and tested is a solid idea.

**Comment by njappboy** [comment]
@ARoomWithABue will telos publish its own docker images @ docker hub?  Current stage2.0 tag still uses docker artifacts that source from the eosio/eos [https://github.com/EOSIO/eos.git repository](https://github.com/Telos-Foundation/telos/blob/fdc4f3a94a84013c84e0eaf867c8c1ae8304c22d/Docker/Dockerfile#L5) and the eosio/eos tooling is used in scripts. Is there a timeline for new docker artifacts? I was just about to try DPOS on the testnet but hit this blocker really quickly.
