### ISSUE TITLE
Add Ricardian Contracts to System Contracts

### ISSUE THREAD

**Issue by ARoomWithABue** [Telos-Foundation/telos#45]
There are currently no Ricardian contracts assigned to actions on any of the systems contracts. There is a syntax described in [this upstream issue](https://github.com/EOSIO/eos/issues/2389). Implementing this syntax on all of our current system contracts would give TELOS governance transparency, and would strength the agreements made by those who use those smart contracts.

**Comment by DouglasHorn** [comment]
I can keep you informed about where these human-language terms are approval-wise. I believe that RegProducer is practically ready.
