### ISSUE TITLE
teclos version client returns a blank version

### ISSUE THREAD

**Issue by jbuice** [Telos-Foundation/telos#47]
tecloes version client returns a blank version

**Comment by ARoomWithABue** [comment]
Can you elaborate on this issue a little more? `telos --version` isn't returning any information?

**Comment by jbuice** [comment]
Correct.

Output looks as follows:


$ teclos version client
Build version: 
$

**Comment by ARoomWithABue** [comment]
The `CMAKE` variable was incorrectly named. I've made the needed adjustment. See the commit below.

7040b29ed4dafc6dddf4b110219af608ebbfa7c6
