### ISSUE TITLE
Rename Keosd

### ISSUE THREAD

**Issue by ARoomWithABue** [Telos-Foundation/telos#5]
Keosd needs to be renamed in order avoid collision with servers that may be running both telos and eos.

- Rename application

**Comment by ARoomWithABue** [comment]
Renaming the application is actually very easy, and necessary. What if, EOSIO and Telos are installed on the same server. You type in the command keosd, which application would be used from path? In order to avoid collision completely, a rename would be required. We will change the default port as well.

**Comment by oviwankenobi** [comment]
in the eventuality eosio and telos are both installed on the same server, they would be installed using different accounts anyway, so different paths. 
so I'd say it is not necessary but it nice to have yes.

**Comment by ARoomWithABue** [comment]
Fair enough, but that is assuming people config their servers intelligently.  What you and I do, isn't exactly what everyone else will do. We both agree that the default port should be changed. I'll separate these in to two different issues with different priorities.
