### ISSUE TITLE
Automatically unreg Producer that misses blocks

### ISSUE THREAD

**Issue by ARoomWithABue** [Telos-Foundation/telos#52]
Need a feature that automatically calls `eosio.system::rmvproducer` when a producer has missed a certain number of blocks.

- [ ] The `missed_blocks` field in the `producer_info` struct is the number of blocks missed within a `M` hour period.
- [ ] If a producer misses `N` blocks within the `M` hour window, then call `rmvproducer`

`N` (the number of blocks missed) can be determined later.
`M` (the number of hours missed blocks are relevant) can be determined later.

**Comment by eedsilva** [comment]
Feature done and merged #71
