### ISSUE TITLE
Calculate the Number of Missed Blocks

### ISSUE THREAD

**Issue by ARoomWithABue** [Telos-Foundation/telos#53]
Using the `eosio.system::onblock` action, determine when a block was missed, and which BP failed to produce that block. Store the last time `onblock` was called in a table (possibly the rotations table), the next time `onblock` is called calculate the difference between the past and current `block_timestamp`s, if the result is `result > 0.5s` then a block was missed. Using the `account_name` of the producer who called `onblock` and the length of time between each `onblock` call we can determine how many blocks were missed, and who missed those blocks.

**Comment by eedsilva** [comment]
Feature done and merged. #71
