### ISSUE TITLE
If tkeosd quits, all wallets are lost

### ISSUE THREAD

**Issue by ARoomWithABue** [Telos-Foundation/telos#57]
If `tkeosd` is running, and it closes. When `tkeosd` is relaunched, all previous wallets stored disappear.

Steps to reproduce:

1. Start an instance of `tkeosd`
2. Create several wallets `['default', 'app', 'personal']`
3. Import several keys into each wallet
4. Terminate `tkeosd` process
5. Start a new `tkeosd` process
6. Run `teclos wallet list`, and see that the output is incorrect

expected output: `['default', 'app', 'personal']`
actual output: `[ ]`

**Comment by DouglasHorn** [comment]
Is this something that was introduced in teclos or is it in cleos as well?

**Comment by ARoomWithABue** [comment]
@DouglasHorn, this doesn't really have anything to do with either. I believe the issue has to do more with `tkeosd` and `keosd`, but more research has to be done. This is just behavior I noticed when `goodblockio1` went down.

**Comment by ARoomWithABue** [comment]
Just an update on this issue. I'm still exploring the possibility of this being an error. I believe that this might be related to the new `open` function added in the `v1.2.0`. It's possible that wallets hide their exists when `tkeosd` is recently started. `unlocking` the named wallet will reveal the wallet if it exists. I will experiment with this further and document reproduction steps.

**Comment by ARoomWithABue** [comment]
Issue is related to intentional implementation of the new wallet closed/open feature.
