### ISSUE TITLE
Issue while running regproducer command

### ISSUE THREAD

**Issue by samarthgaur** [Telos-Foundation/telos#60]
HI Team,
I have followed all the steps and register my node on telos foundation portal. Post registration, I got regproducer command which i ran but it gives me below error. Please help me to resolve it.

2018-09-06T13:51:10.882 thread-0   main.cpp:3011                 main                 ] Failed with error: Assert Exception (10)
!action_type.empty(): Unknown action regproducer in contract eosio

**Comment by ARoomWithABue** [comment]
Thanks for bringing this issue to our attention. Can you send me the command that you executed? I'll need more information to track down the source of your problem. `regproducer` seems so be working on my end.

**Comment by samarthgaur** [comment]
Thanks Peter for your reply. I am using below command - 
Here secure key is my actual key provided by telos foundation registration step.
teclos system regproducer bcwsgnode222 <secure key>

**Comment by ARoomWithABue** [comment]
The command should be formed like this `teclos system regproducer {account_name} {public_key} {company_url}`. I'm assuming you formed your command like this one. If so, do you have the `private_key` that corresponds to the `public_key`?

**Comment by samarthgaur** [comment]
Yeah Peter I am using only the above format of the command. The private key is present inside the config.ini file inside my tn-bcwsgnode222 folder. Do I need to set this private key somewhere  else as well?

**Comment by ARoomWithABue** [comment]
Make sure that you run `teclos wallet import --private-key {private_key}`. In order to create a digital signature for a transaction your the corresponding private key is needed, and that key must be in your wallet.

**Comment by ARoomWithABue** [comment]
`teclos wallet unlock --password {password}` How did you setup your node initially? Is this a manual setup? Have you asked people about this in the telos testnet telegram?

**Comment by ARoomWithABue** [comment]
This doesn't seem like a bug or an issue that needs to be addressed here. I recommend that you join the [Telos Testnet Telegram channel](https://t.me/TelosTestnet). There are a ton of people in there that will be more than willing to help you with this problem. Thanks.
