### ISSUE TITLE
Will you guys hardcode mainnet genesis timestamp and hash?

### ISSUE THREAD

**Issue by eosclassicteam** [Telos-Foundation/telos#62]
If so please do it :smile:

**Comment by DouglasHorn** [comment]
What do you see as the benefit of this?

**Comment by eosclassicteam** [comment]
@DouglasHorn With eosio since there is no genesis block hash hardcoded you should insert them manually and this is annoying for deploying node to cloud services such as aws or docker.

I would like to also request hardcording peers from BPs if possible
