### ISSUE TITLE
Add a way to tell 12 hours ahead of time when a BP's Maint. Window is coming up

### ISSUE THREAD

**Issue by jbuice** [Telos-Foundation/telos#64]
Add a way to tell 12 hours ahead of time when a BP's Maint Window is coming up

**Comment by madalin-barbulescu** [comment]
I will make a comment here to note we will approach this by implementing it on the monitor, since there is no need for extra data stored on the blockchain.

**Comment by madalin-barbulescu** [comment]
This is already on the monitor, closing the issue.
