### ISSUE TITLE
unvoting telosfund account breaks claimrewards after network activation

### ISSUE THREAD

**Issue by jbuice** [Telos-Foundation/telos#65]
teclos -u http://localhost:8888 system claimrewards kainostechtx
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: cannot claim rewards until the chain is activated (at least 15% of all tokens participate in voting)
pending console output:

**Comment by ARoomWithABue** [comment]
This issue was resolve in PR #68
