### ISSUE TITLE
No such file or directory: 'package-linux'

### ISSUE THREAD

**Issue by Kinzowa** [Telos-Foundation/telos#77]
Hello, how can I install the Telos wallet on my Ubuntu 18.04 ? the README.md states to use yarn package-linux but such file doesn't exist.

Thanks

```
xxx:~/Sqrl$ yarn package-linux
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'package-linux'
xxx:~/Sqrl$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
```

**Comment by craigbranscom** [comment]
Were you perhaps reading the wrong documentation? We have never used yarn to build our source, and I couldn't find any build instructions for using it either.

We do have brand new build instructions up, so I would give that a go if you can't get it to work. Closing this issue until then.
